# Environment Settings
env_setting:
  num_gpus: 2
  num_workers: 20
  seed: 1234
  stdout_interval: 10
  checkpoint_interval: 1000
  validation_interval: 1000
  summary_interval: 100
  dist_cfg:
    dist_backend: nccl
    dist_url: tcp://localhost:19477
    world_size: 1

# Datapath Configuration
data_cfg:
  train_clean_json: data/train_clean.json
  train_noisy_json: data/train_noisy.json
  valid_clean_json: data/valid_clean.json
  valid_noisy_json: data/valid_noisy.json
  test_clean_json: data/test_clean.json
  test_noisy_json: data/test_noisy.json

# Training Configuration
training_cfg:
  training_epochs: 200
  batch_size: 2
  learning_rate: 0.0001
  adam_b1: 0.9
  adam_b2: 0.99
  lr_decay: 0.99
  segment_size: 48000
  loss:
    metric: 0.2
    magnitude: 1.0
    phase: 0.3
    complex: 0.15
    time: 0.5
    consistancy: 0.2


# STFT Configuration
stft_cfg:
  sampling_rate: 16000
  n_fft: 400
  hop_size: 100
  win_size: 400

# Model Configuration
model_cfg:
  hid_feature: 64
  compress_factor: 0.3
  num_tfmamba: 4
  d_state: 16
  d_conv: 4
  expand: 4
  norm_epsilon: 0.00001
  beta: 2.0
  input_channel: 2
  output_channel: 1
